import { NgModule } from '@angular/core';
import {
  MatButtonModule,
  MatIconModule,
  MatListModule,
  MatSelectModule,
  MatSidenavModule,
  MatToolbarModule,
  MatCheckboxModule,
  MatGridListModule, 
  MatTabsModule, 
  MatDialogModule, 
  MatExpansionModule, 
  MatInputModule, 
  MatRadioModule, 
  MatCardModule,
  MatSnackBarModule,
  MatTableModule,
  MatPaginatorModule,
  MatProgressSpinnerModule,
  MatChipsModule,
  MatAutocompleteModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatMenuModule,
  MatSortModule,
} from '@angular/material';

const modules = [
  MatToolbarModule,
  MatSidenavModule,
  MatListModule,
  MatButtonModule,
  MatIconModule,
  MatSelectModule,
  MatCheckboxModule,
  MatGridListModule,
  MatTabsModule,
  MatDialogModule,
  MatExpansionModule,
  MatInputModule,
  MatRadioModule,
  MatCardModule,
  MatSnackBarModule,
  MatTableModule,
  MatPaginatorModule,
  MatProgressSpinnerModule,
  MatChipsModule,
  MatDialogModule,
  MatInputModule,
  MatButtonModule,
  MatToolbarModule,
  MatSidenavModule,
  MatTabsModule,
  MatIconModule,
  MatListModule,
  MatExpansionModule,
  MatRadioModule,
  MatTableModule,
  MatCardModule,
  MatSelectModule,
  MatCheckboxModule,
  MatAutocompleteModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatMenuModule,
  MatSortModule,
  MatPaginatorModule,
  MatProgressSpinnerModule,
  MatSnackBarModule,
  MatChipsModule
]
@NgModule({
  imports: modules,
  exports: modules
})
export class MaterialModule { }
